#!/bin/bash
#
# Copyright (c) 2021 Nikita Zlobin <nick87720z@gmail.com>
#
# gitmodules-src-list-gen is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# gitmodules-src-list-gen is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# executable dependencies: git, sed, sort

git submodule foreach --recursive 'printf "%s\n" "$sha1 $displaypath $(git remote get-url origin)"' | sed -n '2~2p' | sort -k2,2

missing="$( git submodule status --recursive | sed -n '/^-/s/-[[:alnum:]]*\ /- /p' )"
if [ "${missing}" ]; then
        printf "\n%s\n" \
                "These submodules can't be described, because are not downloaded:" \
                "$missing" \
                "Run 'git submodule update' to update them."
fi >&2
